;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-indentation
        org-self-insert-command
        smex
        sp--self-insert-command
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ido-switch-buffer
        ))
