;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-paren
        delete-indentation
        insert-semicolon-at-end-of-line
        mc/keyboard-quit
        org-self-insert-command
        self-insert-command
        smex
        sp--self-insert-command
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-backspace
        hydra-js2-refactor/js2r-rename-var-and-exit
        ido-switch-buffer
        js2-indent-bounce
        previous-line
        tom/mcdwim
        yas-expand
        ))
